apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bulbasaur1k/k3s-homelab-config.git
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
