apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bulbasaur1k/k3s-homelab-config.git
    targetRevision: HEAD
    # --- ИЗМЕНЕНИЕ ЗДЕСЬ ---
    # Указываем, что нужно рекурсивно искать YAML во всем репозитории
    path: .
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
