# services/torrserver/02-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: torrserver
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: torrserver
  template:
    metadata:
      labels:
        app: torrserver
    spec:
      containers:
        - name: torrserver
          # Официальный образ от YouROK
          image: ghcr.io/yourok/torrserver:latest
          ports:
            - containerPort: 8090
          volumeMounts:
            - name: data
              mountPath: /opt/ts
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: torrserver-data-pvc
