# services/torrserver/04-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: torrserver-ingress
  namespace: media
spec:
  # Указываем Traefik как Ingress-контроллер
  ingressClassName: traefik
  rules:
    - host: torr.gentoo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: torrserver
                port:
                  number: 80
