# core/rbac.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
# ClusterRole для Argo CD с полными правами
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-admin-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
---
# ClusterRoleBinding для Argo CD Application Controller
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-admin-role
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argocd
