apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 61.3.1
    helm:
      values: |
        alertmanager:
          enabled: false
        grafana:
          enabled: true
          replicas: 1
          adminPassword: "admin"
          persistence:
            enabled: true
            storageClassName: local-path
            size: 2Gi
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - grafana.gentoo.local
        prometheus:
          enabled: true
          prometheusSpec:
            replicas: 1
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  storageClassName: local-path
                  resources:
                    requests:
                      storage: 10Gi
            ruleSelectorNilUsesHelmValues: false
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - prometheus.gentoo.local
        kube-state-metrics:
          enabled: true
        kubeControllerManager:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: false
        # --- ИСПРАВЛЕННАЯ СЕКЦИЯ ДЛЯ NODE-EXPORTER ---
        prometheus-node-exporter:
          enabled: true
          # Используем встроенный механизм чарта для монтирования ФС хоста
          hostRootfs: true
          # Добавляем только аргумент, чтобы node-exporter знал, где искать ФС
          extraArgs:
            - '--path.rootfs=/host' # <-- Обратите внимание, путь по умолчанию /host
