apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    # <-- ИЗМЕНЕНИЕ: Самая последняя версия для совместимости с K8s v1.32
    targetRevision: v29.0.1
    helm:
      values: |
        service:
          type: LoadBalancer
        ingressClass:
          enabled: true
          isDefaultClass: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
